// archive/frontend-aigc-backup-20250927/frontend-aigc/src/components/arbitration/FlowAndChipsViewer.tsx
import React, { useState, useCallback, useMemo } from 'react';
import { Card, Row, Col, Statistic, Progress, Tag, Tooltip, Typography, Divider, Tabs } from 'antd';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, ResponsiveContainer, LineChart, Line, Area, AreaChart } from 'recharts';
import {
  MoneyCollectOutlined,
  RiseOutlined,
  FallOutlined,
  InfoCircleOutlined,
  ThunderboltOutlined
} from '@ant-design/icons';
import { FlowAndChipsViewerProps, FlowAndChipsData, MoneyFlowData, ChipDistributionData } from '../../types/arbitration';
import './FlowAndChipsViewer.css';

const { Text, Title } = Typography;
const { TabPane } = Tabs;

/**
 * 资金流向与筹码分布组件
 * 展示资金流向、龙虎榜和筹码分布数据
 *
 * 核心特性：
 * 1. 资金流向可视化
 * 2. 龙虎榜数据展示
 * 3. 筹码分布图表
 * 4. 交互式数据探索
 */
const FlowAndChipsViewer: React.FC<FlowAndChipsViewerProps> = ({
  data,
  loading = false,
  error = null,
  onFlowHover,
  onChipHover
}) => {
  const [activeTab, setActiveTab] = useState<string>('flow');
  const [hoveredFlow, setHoveredFlow] = useState<MoneyFlowData | null>(null);
  const [hoveredChip, setHoveredChip] = useState<ChipDistributionData | null>(null);

  // 处理资金流向悬浮
  const handleFlowHover = useCallback((flow: MoneyFlowData) => {
    setHoveredFlow(flow);
    onFlowHover?.(flow);
  }, [onFlowHover]);

  // 处理筹码分布悬浮
  const handleChipHover = useCallback((chip: ChipDistributionData) => {
    setHoveredChip(chip);
    onChipHover?.(chip);
  }, [onChipHover]);

  // 获取资金流向数据
  const flowData = useMemo(() => {
    return data?.moneyFlow || null;
  }, [data]);

  // 获取龙虎榜数据
  const topListData = useMemo(() => {
    return data?.topList || [];
  }, [data]);

  // 获取筹码分布数据
  const chipData = useMemo(() => {
    return data?.chipDistribution || [];
  }, [data]);

  // 获取资金流向趋势数据
  const flowTrendData = useMemo(() => {
    if (!flowData) return [];

    return [
      { period: '5日均值', value: flowData.avgNetInflow5d },
      { period: '10日均值', value: flowData.avgNetInflow10d },
      { period: '20日均值', value: flowData.avgNetInflow20d },
      { period: '当前', value: flowData.netAmount }
    ];
  }, [flowData]);

  // 渲染资金流向概览
  const renderFlowOverview = () => {
    if (!flowData) return null;

    const netAmount = flowData.netAmount;
    const netRatio = flowData.netInflowRatio;
    const intensity = flowData.flowIntensity;
    const anomalyScore = flowData.flowAnomalyScore;

    const amountColor = netAmount > 0 ? '#52c41a' : '#ff4d4f';
    const ratioColor = netRatio > 0 ? '#52c41a' : '#ff4d4f';
    const intensityColor = intensity > 0.7 ? '#52c41a' : intensity > 0.4 ? '#faad14' : '#ff4d4f';

    return (
      <Card title="资金流向概览" size="small" className="flow-overview-card">
        <Row gutter={[16, 16]}>
          <Col span={6}>
            <Statistic
              title="净流入金额"
              value={netAmount}
              precision={2}
              valueStyle={{ color: amountColor, fontSize: '20px' }}
              suffix="万元"
              prefix={netAmount > 0 ? <RiseOutlined /> : <FallOutlined />}
            />
          </Col>
          <Col span={6}>
            <Statistic
              title="净流入比例"
              value={netRatio}
              precision={2}
              valueStyle={{ color: ratioColor, fontSize: '20px' }}
              suffix="%"
            />
          </Col>
          <Col span={6}>
            <Statistic
              title="流向强度"
              value={intensity}
              precision={2}
              valueStyle={{ color: intensityColor, fontSize: '20px' }}
              suffix="分"
            />
          </Col>
          <Col span={6}>
            <Statistic
              title="异常评分"
              value={anomalyScore}
              precision={2}
              valueStyle={{ color: anomalyScore > 0.7 ? '#ff4d4f' : '#52c41a', fontSize: '20px' }}
              suffix="分"
            />
          </Col>
        </Row>
      </Card>
    );
  };

  // 渲染资金流向图表
  const renderFlowChart = () => {
    if (!flowData) return null;

    const chartData = [
      { name: '主力', value: flowData.mainForceRatio, amount: flowData.buyAmount },
      { name: '散户', value: flowData.retailRatio, amount: flowData.sellAmount },
      { name: '其他', value: 1 - flowData.mainForceRatio - flowData.retailRatio, amount: 0 }
    ];

    return (
      <Card title="资金流向分析" size="small" className="flow-chart-card">
        <Row gutter={[16, 16]}>
          <Col span={12}>
            <div className="flow-pie-chart">
              <Title level={5}>资金结构分布</Title>
              <ResponsiveContainer width="100%" height={200}>
                <BarChart data={chartData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="name" />
                  <YAxis />
                  <Tooltip formatter={(value, name) => [`${(value * 100).toFixed(1)}%`, name]} />
                  <Bar dataKey="value" fill="#1890ff" />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </Col>
          <Col span={12}>
            <div className="flow-trend-chart">
              <Title level={5}>流向趋势对比</Title>
              <ResponsiveContainer width="100%" height={200}>
                <LineChart data={flowTrendData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="period" />
                  <YAxis />
                  <Tooltip formatter={(value) => [`${value.toFixed(2)}万元`, '净流入']} />
                  <Line type="monotone" dataKey="value" stroke="#52c41a" strokeWidth={2} />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </Col>
        </Row>
      </Card>
    );
  };

  // 渲染龙虎榜数据
  const renderTopList = () => {
    if (topListData.length === 0) return null;

    return (
      <Card title="龙虎榜数据" size="small" className="top-list-card">
        <div className="top-list-content">
          {topListData.map((item, index) => (
            <div key={index} className="top-list-item">
              <div className="top-list-header">
                <Text strong>{item.seatName}</Text>
                <Tag color={item.seatType === 'buy' ? 'green' : 'red'}>
                  {item.seatType === 'buy' ? '买入' : '卖出'}
                </Tag>
              </div>
              <div className="top-list-details">
                <Row gutter={[8, 8]}>
                  <Col span={8}>
                    <Text type="secondary">净额: </Text>
                    <Text strong style={{ color: item.netAmount > 0 ? '#52c41a' : '#ff4d4f' }}>
                      {item.netAmount.toFixed(2)}万元
                    </Text>
                  </Col>
                  <Col span={8}>
                    <Text type="secondary">买入: </Text>
                    <Text>{item.buyAmount.toFixed(2)}万元</Text>
                  </Col>
                  <Col span={8}>
                    <Text type="secondary">卖出: </Text>
                    <Text>{item.sellAmount.toFixed(2)}万元</Text>
                  </Col>
                </Row>
                <div className="top-list-meta">
                  <Text type="secondary">排名: {item.netRank} | 占比: {(item.netRatio * 100).toFixed(1)}%</Text>
                </div>
              </div>
            </div>
          ))}
        </div>
      </Card>
    );
  };

  // 渲染筹码分布图表
  const renderChipDistribution = () => {
    if (chipData.length === 0) return null;

    const chartData = chipData.map(item => ({
      price: item.priceMedian,
      quantity: item.chipQuantity,
      ratio: item.chipRatio,
      cost: item.averageCost,
      profitLoss: item.profitLossRatio
    }));

    return (
      <Card title="筹码分布分析" size="small" className="chip-distribution-card">
        <Row gutter={[16, 16]}>
          <Col span={12}>
            <div className="chip-distribution-chart">
              <Title level={5}>筹码分布图</Title>
              <ResponsiveContainer width="100%" height={300}>
                <AreaChart data={chartData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="price" />
                  <YAxis />
                  <Tooltip
                    formatter={(value, name) => [
                      name === 'quantity' ? `${value}万股` : `${(value * 100).toFixed(1)}%`,
                      name === 'quantity' ? '筹码数量' : '筹码比例'
                    ]}
                  />
                  <Area
                    type="monotone"
                    dataKey="quantity"
                    stroke="#1890ff"
                    fill="#1890ff"
                    fillOpacity={0.6}
                  />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          </Col>
          <Col span={12}>
            <div className="chip-cost-analysis">
              <Title level={5}>成本分析</Title>
              <div className="cost-metrics">
                {chipData.map((item, index) => (
                  <div key={index} className="cost-metric">
                    <div className="cost-header">
                      <Text strong>价格区间: {item.priceLower}-{item.priceUpper}</Text>
                      <Text type="secondary">中位数: {item.priceMedian}</Text>
                    </div>
                    <div className="cost-details">
                      <Row gutter={[8, 8]}>
                        <Col span={12}>
                          <Text type="secondary">平均成本: </Text>
                          <Text strong>{item.averageCost.toFixed(2)}</Text>
                        </Col>
                        <Col span={12}>
                          <Text type="secondary">盈亏比例: </Text>
                          <Text strong style={{ color: item.profitLossRatio > 0 ? '#52c41a' : '#ff4d4f' }}>
                            {(item.profitLossRatio * 100).toFixed(1)}%
                          </Text>
                        </Col>
                      </Row>
                      <div className="cost-concentration">
                        <Text type="secondary">集中度: </Text>
                        <Progress
                          percent={item.costConcentration * 100}
                          size="small"
                          strokeColor="#1890ff"
                        />
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </Col>
        </Row>
      </Card>
    );
  };

  // 渲染综合分析
  const renderComprehensiveAnalysis = () => {
    if (!flowData) return null;

    const analysis = {
      flowTrend: flowData.flowTrend > 0 ? '上升' : '下降',
      chipConcentration: chipData.length > 0 ? chipData[0].costConcentration : 0,
      mainForceRatio: flowData.mainForceRatio,
      retailRatio: flowData.retailRatio
    };

    return (
      <Card title="综合分析" size="small" className="comprehensive-analysis-card">
        <div className="analysis-content">
          <Row gutter={[16, 16]}>
            <Col span={8}>
              <div className="analysis-item">
                <Text strong>资金流向趋势</Text>
                <div className="analysis-value">
                  <Tag color={flowData.flowTrend > 0 ? 'green' : 'red'}>
                    {analysis.flowTrend}
                  </Tag>
                </div>
              </div>
            </Col>
            <Col span={8}>
              <div className="analysis-item">
                <Text strong>筹码集中度</Text>
                <div className="analysis-value">
                  <Progress
                    percent={analysis.chipConcentration * 100}
                    size="small"
                    strokeColor="#1890ff"
                  />
                </div>
              </div>
            </Col>
            <Col span={8}>
              <div className="analysis-item">
                <Text strong>主力散户比例</Text>
                <div className="analysis-value">
                  <Text>主力: {(analysis.mainForceRatio * 100).toFixed(1)}%</Text>
                  <br />
                  <Text>散户: {(analysis.retailRatio * 100).toFixed(1)}%</Text>
                </div>
              </div>
            </Col>
          </Row>
        </div>
      </Card>
    );
  };

  if (error) {
    return (
      <div className="flow-and-chips-viewer">
        <div className="error-state">
          <Text type="danger">加载失败: {error}</Text>
        </div>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="flow-and-chips-viewer">
        <div className="loading-state">
          <Text>加载资金流向数据中...</Text>
        </div>
      </div>
    );
  }

  return (
    <div className="flow-and-chips-viewer">
      <Tabs activeKey={activeTab} onChange={setActiveTab}>
        <TabPane tab="资金流向" key="flow">
          {renderFlowOverview()}
          <Divider />
          {renderFlowChart()}
        </TabPane>
        <TabPane tab="龙虎榜" key="toplist">
          {renderTopList()}
        </TabPane>
        <TabPane tab="筹码分布" key="chips">
          {renderChipDistribution()}
        </TabPane>
        <TabPane tab="综合分析" key="analysis">
          {renderComprehensiveAnalysis()}
        </TabPane>
      </Tabs>
    </div>
  );
};

export default FlowAndChipsViewer;

// packages/frontend-main/src/components/admin/FlowAndChipsViewer.vue
<template>
  <div class="flow-chips-viewer">
    <!-- 标签页切换 -->
    <el-tabs
      v-model="activeTab"
      class="main-tabs"
    >
      <!-- 资金流向标签页 -->
      <el-tab-pane
        label="资金流向"
        name="flow"
      >
        <div class="flow-content">
          <!-- 资金流向概览 -->
          <div
            v-if="flowData"
            class="flow-overview"
          >
            <el-card class="overview-card">
              <template #header>
                <h3>资金流向概览</h3>
              </template>

              <el-row :gutter="16">
                <el-col :span="6">
                  <el-statistic
                    title="净流入金额"
                    :value="flowData.netAmount"
                    :precision="2"
                    suffix="万元"
                    :value-style="{ color: flowData.netAmount > 0 ? '#67c23a' : '#f56c6c' }"
                  >
                    <template #prefix>
                      <el-icon :color="flowData.netAmount > 0 ? '#67c23a' : '#f56c6c'">
                        <component :is="flowData.netAmount > 0 ? 'TrendCharts' : 'TrendCharts'" />
                      </el-icon>
                    </template>
                  </el-statistic>
                </el-col>
                <el-col :span="6">
                  <el-statistic
                    title="净流入比例"
                    :value="flowData.netInflowRatio"
                    :precision="2"
                    suffix="%"
                    :value-style="{ color: flowData.netInflowRatio > 0 ? '#67c23a' : '#f56c6c' }"
                  />
                </el-col>
                <el-col :span="6">
                  <el-statistic
                    title="流向强度"
                    :value="flowData.flowIntensity"
                    :precision="2"
                    :value-style="{ color: getIntensityColor(flowData.flowIntensity) }"
                  />
                </el-col>
                <el-col :span="6">
                  <el-statistic
                    title="异常评分"
                    :value="flowData.flowAnomalyScore"
                    :precision="2"
                    :value-style="{ color: getAnomalyColor(flowData.flowAnomalyScore) }"
                  />
                </el-col>
              </el-row>
            </el-card>
          </div>

          <!-- 资金流向趋势图 -->
          <div
            v-if="flowData"
            class="flow-trend"
          >
            <el-card>
              <template #header>
                <h4>资金流向趋势</h4>
              </template>
              <div class="chart-container">
                <v-chart
                  :option="flowTrendChartOption"
                  style="height: 300px;"
                />
              </div>
            </el-card>
          </div>

          <!-- 资金流向详情 -->
          <div
            v-if="flowData"
            class="flow-details"
          >
            <el-card>
              <template #header>
                <h4>资金流向详情</h4>
              </template>

              <el-row :gutter="16">
                <el-col :span="12">
                  <div class="detail-item">
                    <span class="label">主力占比:</span>
                    <el-progress
                      :percentage="flowData.mainForceRatio * 100"
                      :color="getProgressColor(flowData.mainForceRatio)"
                    />
                  </div>
                </el-col>
                <el-col :span="12">
                  <div class="detail-item">
                    <span class="label">散户占比:</span>
                    <el-progress
                      :percentage="flowData.retailRatio * 100"
                      :color="getProgressColor(flowData.retailRatio)"
                    />
                  </div>
                </el-col>
              </el-row>
            </el-card>
          </div>
        </div>
      </el-tab-pane>

      <!-- 龙虎榜标签页 -->
      <el-tab-pane
        label="龙虎榜"
        name="toplist"
      >
        <div class="toplist-content">
          <el-card v-if="topListData.length > 0">
            <template #header>
              <h4>龙虎榜数据</h4>
            </template>

            <el-table
              :data="topListData"
              stripe
            >
              <el-table-column
                prop="seatName"
                label="席位名称"
                width="150"
              />
              <el-table-column
                prop="seatCategory"
                label="席位类型"
                width="100"
              >
                <template #default="{ row }">
                  <el-tag :type="getSeatTypeColor(row.seatType)">
                    {{ getSeatTypeLabel(row.seatType) }}
                  </el-tag>
                </template>
              </el-table-column>
              <el-table-column
                prop="buyAmount"
                label="买入金额"
                width="120"
              >
                <template #default="{ row }">
                  <span style="color: #67c23a;">{{ formatAmount(row.buyAmount) }}</span>
                </template>
              </el-table-column>
              <el-table-column
                prop="sellAmount"
                label="卖出金额"
                width="120"
              >
                <template #default="{ row }">
                  <span style="color: #f56c6c;">{{ formatAmount(row.sellAmount) }}</span>
                </template>
              </el-table-column>
              <el-table-column
                prop="netAmount"
                label="净买入"
                width="120"
              >
                <template #default="{ row }">
                  <span :style="{ color: row.netAmount > 0 ? '#67c23a' : '#f56c6c' }">
                    {{ formatAmount(row.netAmount) }}
                  </span>
                </template>
              </el-table-column>
              <el-table-column
                prop="priceImpactScore"
                label="价格影响"
                width="100"
              >
                <template #default="{ row }">
                  <el-tag :type="getScoreType(row.priceImpactScore)">
                    {{ (row.priceImpactScore * 100).toFixed(1) }}%
                  </el-tag>
                </template>
              </el-table-column>
            </el-table>
          </el-card>

          <el-empty
            v-else
            description="暂无龙虎榜数据"
          />
        </div>
      </el-tab-pane>

      <!-- 筹码分布标签页 -->
      <el-tab-pane
        label="筹码分布"
        name="chips"
      >
        <div class="chips-content">
          <el-card v-if="chipData.length > 0">
            <template #header>
              <h4>筹码分布分析</h4>
            </template>

            <!-- 筹码分布图表 -->
            <div class="chart-container">
              <v-chart
                :option="chipDistributionChartOption"
                style="height: 400px;"
              />
            </div>

            <!-- 筹码分布详情 -->
            <div class="chip-details">
              <el-row :gutter="16">
                <el-col
                  v-for="chip in chipData"
                  :key="chip.distributionId"
                  :span="8"
                >
                  <el-card
                    class="chip-card"
                    @mouseenter="handleChipHover(chip)"
                  >
                    <div class="chip-header">
                      <span class="chip-type">{{ getChipTypeLabel(chip.distributionType) }}</span>
                      <el-tag :type="getChipStatusType(chip.chipStatus)">
                        {{ getChipStatusLabel(chip.chipStatus) }}
                      </el-tag>
                    </div>
                    <div class="chip-content">
                      <div class="chip-price-range">
                        <span class="price-label">价格区间:</span>
                        <span class="price-value">{{ chip.priceLower }} - {{ chip.priceUpper }}</span>
                      </div>
                      <div class="chip-quantity">
                        <span class="quantity-label">筹码数量:</span>
                        <span class="quantity-value">{{ formatAmount(chip.chipQuantity) }}</span>
                      </div>
                      <div class="chip-ratio">
                        <span class="ratio-label">占比:</span>
                        <el-progress
                          :percentage="chip.chipRatio * 100"
                          :color="getChipRatioColor(chip.chipRatio)"
                          :show-text="false"
                        />
                        <span class="ratio-value">{{ (chip.chipRatio * 100).toFixed(1) }}%</span>
                      </div>
                    </div>
                  </el-card>
                </el-col>
              </el-row>
            </div>
          </el-card>

          <el-empty
            v-else
            description="暂无筹码分布数据"
          />
        </div>
      </el-tab-pane>
    </el-tabs>

    <!-- 空状态 -->
    <el-empty
      v-if="!loading && !flowData && topListData.length === 0 && chipData.length === 0"
      description="暂无资金流向和筹码数据"
    />

    <!-- 加载状态 -->
    <div
      v-if="loading"
      class="loading"
    >
      <el-skeleton
        :rows="4"
        animated
      />
    </div>

    <!-- 错误状态 -->
    <el-alert
      v-if="error"
      type="error"
      :title="error"
      show-icon
      closable
      @close="handleErrorClose"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { use } from 'echarts/core';
import { CanvasRenderer } from 'echarts/renderers';
import { BarChart, LineChart } from 'echarts/charts';
import {
  TitleComponent,
  TooltipComponent,
  LegendComponent,
  GridComponent
} from 'echarts/components';
import VChart from 'vue-echarts';
import { TrendCharts } from '@element-plus/icons-vue';
import type { FlowAndChipsViewerProps, FlowAndChipsData, MoneyFlowData, ChipDistributionData } from '@/types/arbitration';

// 注册 ECharts 组件
use([
  CanvasRenderer,
  BarChart,
  LineChart,
  TitleComponent,
  TooltipComponent,
  LegendComponent,
  GridComponent
]);

// ==================== Props ====================
const props = withDefaults(defineProps<FlowAndChipsViewerProps>(), {
  loading: false,
  error: null,
  onFlowHover: () => {},
  onChipHover: () => {}
});

// ==================== 响应式数据 ====================
const activeTab = ref('flow');

// ==================== 计算属性 ====================
const flowData = computed(() => {
  return props.data?.moneyFlow || null;
});

const topListData = computed(() => {
  return props.data?.topList || [];
});

const chipData = computed(() => {
  return props.data?.chipDistribution || [];
});

const flowTrendData = computed(() => {
  if (!flowData.value) return [];

  return [
    { period: '5日均值', value: flowData.value.avgNetInflow5d },
    { period: '10日均值', value: flowData.value.avgNetInflow10d },
    { period: '20日均值', value: flowData.value.avgNetInflow20d },
    { period: '当前', value: flowData.value.netAmount }
  ];
});

const flowTrendChartOption = computed(() => ({
  title: {
    text: '资金流向趋势对比',
    left: 'center'
  },
  tooltip: {
    trigger: 'axis'
  },
  xAxis: {
    type: 'category',
    data: flowTrendData.value.map(item => item.period)
  },
  yAxis: {
    type: 'value',
    name: '万元'
  },
  series: [
    {
      name: '净流入金额',
      type: 'bar',
      data: flowTrendData.value.map(item => item.value),
      itemStyle: {
        color: function(params: any) {
          return params.value > 0 ? '#67c23a' : '#f56c6c';
        }
      }
    }
  ]
}));

const chipDistributionChartOption = computed(() => {
  if (chipData.value.length === 0) return {};

  const data = chipData.value.map(chip => ({
    name: `${chip.priceLower}-${chip.priceUpper}`,
    value: chip.chipQuantity,
    priceRange: `${chip.priceLower}-${chip.priceUpper}`,
    ratio: chip.chipRatio
  }));

  return {
    title: {
      text: '筹码分布图',
      left: 'center'
    },
    tooltip: {
      trigger: 'item',
      formatter: '{a} <br/>{b}: {c} ({d}%)'
    },
    series: [
      {
        name: '筹码分布',
        type: 'pie',
        radius: '50%',
        data: data,
        emphasis: {
          itemStyle: {
            shadowBlur: 10,
            shadowOffsetX: 0,
            shadowColor: 'rgba(0, 0, 0, 0.5)'
          }
        }
      }
    ]
  };
});

// ==================== 方法 ====================
const handleFlowHover = (flow: MoneyFlowData) => {
  props.onFlowHover?.(flow);
};

const handleChipHover = (chip: ChipDistributionData) => {
  props.onChipHover?.(chip);
};

const getIntensityColor = (intensity: number) => {
  if (intensity > 0.7) return '#67c23a';
  if (intensity > 0.4) return '#e6a23c';
  return '#f56c6c';
};

const getAnomalyColor = (score: number) => {
  if (score > 0.7) return '#f56c6c';
  if (score > 0.4) return '#e6a23c';
  return '#67c23a';
};

const getProgressColor = (value: number) => {
  if (value > 0.7) return '#67c23a';
  if (value > 0.4) return '#e6a23c';
  return '#f56c6c';
};

const getSeatTypeColor = (type: string) => {
  const colors: Record<string, string> = {
    buy: 'success',
    sell: 'danger',
    net: 'info'
  };
  return colors[type] || 'info';
};

const getSeatTypeLabel = (type: string) => {
  const labels: Record<string, string> = {
    buy: '买入',
    sell: '卖出',
    net: '净买入'
  };
  return labels[type] || type;
};

const getScoreType = (score: number) => {
  if (score > 0.7) return 'danger';
  if (score > 0.4) return 'warning';
  return 'success';
};

const getChipTypeLabel = (type: string) => {
  const labels: Record<string, string> = {
    cost_distribution: '成本分布',
    volume_distribution: '成交量分布',
    price_distribution: '价格分布'
  };
  return labels[type] || type;
};

const getChipStatusType = (status: string) => {
  const types: Record<string, string> = {
    active: 'success',
    locked: 'warning',
    floating: 'info'
  };
  return types[status] || 'info';
};

const getChipStatusLabel = (status: string) => {
  const labels: Record<string, string> = {
    active: '活跃',
    locked: '锁定',
    floating: '浮动'
  };
  return labels[status] || status;
};

const getChipRatioColor = (ratio: number) => {
  if (ratio > 0.3) return '#67c23a';
  if (ratio > 0.1) return '#e6a23c';
  return '#f56c6c';
};

const formatAmount = (amount: number) => {
  if (amount >= 10000) {
    return (amount / 10000).toFixed(1) + '万';
  }
  return amount.toFixed(0);
};

const handleErrorClose = () => {
  // 错误处理逻辑
};
</script>

<style scoped>
.flow-chips-viewer {
  height: 100%;
  overflow-y: auto;
}

.main-tabs {
  height: 100%;
}

.flow-content,
.toplist-content,
.chips-content {
  height: 100%;
  overflow-y: auto;
}

.flow-overview {
  margin-bottom: 20px;
}

.overview-card h3 {
  margin: 0;
  color: #333;
}

.flow-trend,
.chip-details {
  margin-bottom: 20px;
}

.chart-container {
  background: #fff;
  border-radius: 6px;
  padding: 16px;
}

.detail-item {
  margin-bottom: 16px;
}

.detail-item .label {
  display: block;
  margin-bottom: 8px;
  font-weight: 500;
  color: #333;
}

.chip-card {
  margin-bottom: 16px;
  cursor: pointer;
  transition: all 0.3s ease;
}

.chip-card:hover {
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
}

.chip-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 12px;
}

.chip-type {
  font-weight: 500;
  color: #333;
}

.chip-content {
  space-y: 8px;
}

.chip-price-range,
.chip-quantity,
.chip-ratio {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 8px;
}

.price-label,
.quantity-label,
.ratio-label {
  font-size: 12px;
  color: #666;
}

.price-value,
.quantity-value,
.ratio-value {
  font-weight: 500;
  color: #333;
}

.chip-ratio {
  gap: 8px;
}

.ratio-value {
  min-width: 40px;
  text-align: right;
}

.loading {
  padding: 20px;
}

/* 滚动条样式 */
.flow-chips-viewer::-webkit-scrollbar,
.flow-content::-webkit-scrollbar,
.toplist-content::-webkit-scrollbar,
.chips-content::-webkit-scrollbar {
  width: 6px;
}

.flow-chips-viewer::-webkit-scrollbar-track,
.flow-content::-webkit-scrollbar-track,
.toplist-content::-webkit-scrollbar-track,
.chips-content::-webkit-scrollbar-track {
  background: #f1f1f1;
  border-radius: 3px;
}

.flow-chips-viewer::-webkit-scrollbar-thumb,
.flow-content::-webkit-scrollbar-thumb,
.toplist-content::-webkit-scrollbar-thumb,
.chips-content::-webkit-scrollbar-thumb {
  background: #c1c1c1;
  border-radius: 3px;
}

.flow-chips-viewer::-webkit-scrollbar-thumb:hover,
.flow-content::-webkit-scrollbar-thumb:hover,
.toplist-content::-webkit-scrollbar-thumb:hover,
.chips-content::-webkit-scrollbar-thumb:hover {
  background: #a8a8a8;
}
</style>
