// archive/frontend-aigc-backup-20250927/frontend-aigc/src/components/arbitration/QuantSignalDashboard.tsx
import React, { useState, useCallback, useMemo } from 'react';
import { Card, Row, Col, Statistic, Progress, Tag, Tooltip, Typography, Divider } from 'antd';
import { Gauge, GaugeConfig } from '@ant-design/charts';
import { Radar, RadarConfig } from '@ant-design/charts';
import {
  ThunderboltOutlined,
  RiseOutlined,
  FallOutlined,
  InfoCircleOutlined,
  WarningOutlined
} from '@ant-design/icons';
import { QuantSignalDashboardProps, QuantSignalsData } from '../../types/arbitration';
import './QuantSignalDashboard.css';

const { Text, Title } = Typography;

/**
 * 量化信号仪表盘组件
 * 展示当日量化信号和市场背景，支持可视化分析
 *
 * 核心特性：
 * 1. 仪表盘图表展示Z-Score
 * 2. 雷达图展示多维度信号
 * 3. 智能信号强度评估
 * 4. 交互式数据探索
 */
const QuantSignalDashboard: React.FC<QuantSignalDashboardProps> = ({
  data,
  loading = false,
  error = null,
  onSignalHover,
  onSignalClick
}) => {
  const [hoveredSignal, setHoveredSignal] = useState<string | null>(null);

  // 处理信号悬浮
  const handleSignalHover = useCallback((signal: string, value: number) => {
    setHoveredSignal(signal);
    onSignalHover?.(signal, value);
  }, [onSignalHover]);

  // 处理信号点击
  const handleSignalClick = useCallback((signal: QuantSignalsData) => {
    onSignalClick?.(signal);
  }, [onSignalClick]);

  // 获取最新信号数据
  const latestSignal = useMemo(() => {
    return data.length > 0 ? data[0] : null;
  }, [data]);

  // 获取信号强度等级
  const getSignalStrength = (value: number) => {
    if (Math.abs(value) >= 2) return { level: 'strong', color: '#ff4d4f' };
    if (Math.abs(value) >= 1.5) return { level: 'medium', color: '#faad14' };
    if (Math.abs(value) >= 1) return { level: 'weak', color: '#52c41a' };
    return { level: 'neutral', color: '#d9d9d9' };
  };

  // 获取信号方向
  const getSignalDirection = (value: number) => {
    if (value > 0) return { direction: 'up', icon: <TrendingUpOutlined />, color: '#52c41a' };
    if (value < 0) return { direction: 'down', icon: <TrendingDownOutlined />, color: '#ff4d4f' };
    return { direction: 'neutral', icon: null, color: '#d9d9d9' };
  };

  // 渲染Z-Score仪表盘
  const renderZScoreGauge = (title: string, value: number, color: string) => {
    const config: GaugeChartProps = {
      percent: Math.min(Math.abs(value) / 3, 1),
      range: {
        color: color,
      },
      indicator: {
        pointer: {
          style: {
            stroke: color,
          },
        },
        pin: {
          style: {
            stroke: color,
          },
        },
      },
      statistic: {
        content: {
          style: {
            whiteSpace: 'pre-wrap',
            overflow: 'hidden',
            textOverflow: 'ellipsis',
          },
          formatter: () => `${value.toFixed(2)}`,
        },
      },
    };

    return (
      <Card size="small" className="gauge-card">
        <Title level={5}>{title}</Title>
        <GaugeChart {...config} height={120} />
        <div className="gauge-footer">
          <Text type="secondary">Z-Score: {value.toFixed(2)}</Text>
        </div>
      </Card>
    );
  };

  // 渲染个股信号
  const renderIndividualSignals = () => {
    if (!latestSignal) return null;

    const signals = [
      {
        title: '收益率Z-Score',
        value: latestSignal.returnZScore,
        description: '个股收益率相对历史均值的偏离程度'
      },
      {
        title: '成交量Z-Score',
        value: latestSignal.volumeZScore,
        description: '成交量相对历史均值的偏离程度'
      },
      {
        title: '动量Z-Score',
        value: latestSignal.momentumZScore,
        description: '价格动量相对历史均值的偏离程度'
      },
      {
        title: '波动率Z-Score',
        value: latestSignal.volatilityZScore,
        description: '价格波动率相对历史均值的偏离程度'
      }
    ];

    return (
      <Card title="个股信号" size="small" className="individual-signals-card">
        <Row gutter={[16, 16]}>
          {signals.map((signal, index) => {
            const strength = getSignalStrength(signal.value);
            const direction = getSignalDirection(signal.value);

            return (
              <Col span={6} key={index}>
                <div
                  className={`signal-item ${hoveredSignal === signal.title ? 'hovered' : ''}`}
                  onMouseEnter={() => handleSignalHover(signal.title, signal.value)}
                  onMouseLeave={() => setHoveredSignal(null)}
                  onClick={() => handleSignalClick(latestSignal)}
                >
                  <div className="signal-header">
                    <Text strong>{signal.title}</Text>
                    <Tooltip title={signal.description}>
                      <InfoCircleOutlined className="info-icon" />
                    </Tooltip>
                  </div>
                  <div className="signal-value">
                    <Text
                      style={{
                        fontSize: '24px',
                        color: direction.color,
                        fontWeight: 'bold'
                      }}
                    >
                      {direction.icon} {signal.value.toFixed(2)}
                    </Text>
                  </div>
                  <div className="signal-strength">
                    <Tag color={strength.color}>
                      {strength.level === 'strong' ? '强' :
                       strength.level === 'medium' ? '中' :
                       strength.level === 'weak' ? '弱' : '中性'}
                    </Tag>
                  </div>
                </div>
              </Col>
            );
          })}
        </Row>
      </Card>
    );
  };

  // 渲染市场背景信号
  const renderMarketSignals = () => {
    if (!latestSignal) return null;

    const signals = [
      {
        title: '宏观风险Z-Score',
        value: latestSignal.macroRiskZScore,
        description: '宏观风险偏好相对历史均值的偏离程度'
      },
      {
        title: '市场风格Z-Score',
        value: latestSignal.marketStyleZScore,
        description: '市场风格因子相对历史均值的偏离程度'
      },
      {
        title: '行业轮动Z-Score',
        value: latestSignal.industryRotationZScore,
        description: '行业轮动相对历史均值的偏离程度'
      },
      {
        title: '概念Z-Score',
        value: latestSignal.conceptZScore,
        description: '概念板块相对历史均值的偏离程度'
      }
    ];

    return (
      <Card title="市场背景信号" size="small" className="market-signals-card">
        <Row gutter={[16, 16]}>
          {signals.map((signal, index) => {
            const strength = getSignalStrength(signal.value);
            const direction = getSignalDirection(signal.value);

            return (
              <Col span={6} key={index}>
                <div
                  className={`signal-item ${hoveredSignal === signal.title ? 'hovered' : ''}`}
                  onMouseEnter={() => handleSignalHover(signal.title, signal.value)}
                  onMouseLeave={() => setHoveredSignal(null)}
                  onClick={() => handleSignalClick(latestSignal)}
                >
                  <div className="signal-header">
                    <Text strong>{signal.title}</Text>
                    <Tooltip title={signal.description}>
                      <InfoCircleOutlined className="info-icon" />
                    </Tooltip>
                  </div>
                  <div className="signal-value">
                    <Text
                      style={{
                        fontSize: '20px',
                        color: direction.color,
                        fontWeight: 'bold'
                      }}
                    >
                      {direction.icon} {signal.value.toFixed(2)}
                    </Text>
                  </div>
                  <div className="signal-strength">
                    <Tag color={strength.color}>
                      {strength.level === 'strong' ? '强' :
                       strength.level === 'medium' ? '中' :
                       strength.level === 'weak' ? '弱' : '中性'}
                    </Tag>
                  </div>
                </div>
              </Col>
            );
          })}
        </Row>
      </Card>
    );
  };

  // 渲染管理层可信度因子
  const renderManagementFactors = () => {
    if (!latestSignal) return null;

    const factors = [
      {
        title: 'MD&A履约率',
        value: latestSignal.mdaFulfillmentRate,
        suffix: '%',
        description: '管理层承诺的履约完成率'
      },
      {
        title: '管理层可信度',
        value: latestSignal.managementCredibilityScore,
        suffix: '分',
        description: '管理层整体可信度评分'
      },
      {
        title: '披露质量',
        value: latestSignal.disclosureQualityScore,
        suffix: '分',
        description: '信息披露质量评分'
      },
      {
        title: '财务透明度',
        value: latestSignal.financialTransparencyScore,
        suffix: '分',
        description: '财务数据透明度评分'
      }
    ];

    return (
      <Card title="管理层可信度因子" size="small" className="management-factors-card">
        <Row gutter={[16, 16]}>
          {factors.map((factor, index) => {
            const color = factor.value > 0.7 ? '#52c41a' : factor.value > 0.5 ? '#faad14' : '#ff4d4f';

            return (
              <Col span={6} key={index}>
                <div className="factor-item">
                  <div className="factor-header">
                    <Text strong>{factor.title}</Text>
                    <Tooltip title={factor.description}>
                      <InfoCircleOutlined className="info-icon" />
                    </Tooltip>
                  </div>
                  <div className="factor-value">
                    <Text
                      style={{
                        fontSize: '24px',
                        color: color,
                        fontWeight: 'bold'
                      }}
                    >
                      {factor.value.toFixed(2)}{factor.suffix}
                    </Text>
                  </div>
                  <div className="factor-progress">
                    <Progress
                      percent={factor.value * 100}
                      strokeColor={color}
                      showInfo={false}
                      size="small"
                    />
                  </div>
                </div>
              </Col>
            );
          })}
        </Row>
      </Card>
    );
  };

  // 渲染综合评分
  const renderOverallScore = () => {
    if (!latestSignal) return null;

    const overallScore = latestSignal.overallSignalStrength;
    const confidence = latestSignal.signalConfidence;
    const validityDays = latestSignal.validityDays;

    const scoreColor = overallScore > 0.7 ? '#52c41a' : overallScore > 0.4 ? '#faad14' : '#ff4d4f';
    const confidenceColor = confidence > 0.8 ? '#52c41a' : confidence > 0.6 ? '#faad14' : '#ff4d4f';

    return (
      <Card title="综合评分" size="small" className="overall-score-card">
        <Row gutter={[16, 16]}>
          <Col span={8}>
            <Statistic
              title="信号强度"
              value={overallScore}
              precision={2}
              valueStyle={{ color: scoreColor, fontSize: '24px' }}
              suffix="分"
            />
          </Col>
          <Col span={8}>
            <Statistic
              title="信号置信度"
              value={confidence}
              precision={2}
              valueStyle={{ color: confidenceColor, fontSize: '24px' }}
              suffix="分"
            />
          </Col>
          <Col span={8}>
            <Statistic
              title="有效期"
              value={validityDays}
              valueStyle={{ fontSize: '24px' }}
              suffix="天"
            />
          </Col>
        </Row>

        <div className="score-warning">
          {overallScore < 0.3 && (
            <div className="warning-item">
              <WarningOutlined style={{ color: '#ff4d4f' }} />
              <Text type="danger">信号强度较弱，建议谨慎操作</Text>
            </div>
          )}
          {confidence < 0.6 && (
            <div className="warning-item">
              <WarningOutlined style={{ color: '#faad14' }} />
              <Text type="warning">信号置信度较低，建议进一步验证</Text>
            </div>
          )}
        </div>
      </Card>
    );
  };

  if (error) {
    return (
      <div className="quant-signal-dashboard">
        <div className="error-state">
          <Text type="danger">加载失败: {error}</Text>
        </div>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="quant-signal-dashboard">
        <div className="loading-state">
          <Text>加载量化信号中...</Text>
        </div>
      </div>
    );
  }

  return (
    <div className="quant-signal-dashboard">
      <div className="dashboard-content">
        {renderIndividualSignals()}

        <Divider />

        {renderMarketSignals()}

        <Divider />

        {renderManagementFactors()}

        <Divider />

        {renderOverallScore()}
      </div>
    </div>
  );
};

export default QuantSignalDashboard;

// packages/frontend-main/src/components/admin/QuantSignalDashboard.vue
<template>
  <div class="quant-signal-dashboard">
    <!-- 信号概览 -->
    <div
      v-if="latestSignal"
      class="signal-overview"
    >
      <el-card class="overview-card">
        <template #header>
          <div class="card-header">
            <h3>量化信号概览</h3>
            <el-tag :type="getSignalStatusType(latestSignal.status)">
              {{ getSignalStatusLabel(latestSignal.status) }}
            </el-tag>
          </div>
        </template>

        <el-row :gutter="16">
          <el-col :span="8">
            <el-statistic
              title="综合信号强度"
              :value="latestSignal.overallSignalStrength"
              suffix="分"
              :precision="1"
            />
          </el-col>
          <el-col :span="8">
            <el-statistic
              title="信号置信度"
              :value="latestSignal.signalConfidence"
              suffix="%"
              :precision="1"
            />
          </el-col>
          <el-col :span="8">
            <el-statistic
              title="有效期"
              :value="latestSignal.validityDays"
              suffix="天"
            />
          </el-col>
        </el-row>
      </el-card>
    </div>

    <!-- 个股信号 -->
    <div class="individual-signals">
      <h4>个股信号</h4>
      <el-row :gutter="16">
        <el-col
          v-for="signal in individualSignals"
          :key="signal.name"
          :span="6"
        >
          <el-card
            class="signal-card"
            @mouseenter="handleSignalHover(signal.name, signal.value)"
          >
            <div class="signal-header">
              <span class="signal-name">{{ signal.name }}</span>
              <el-tag
                :type="getSignalStrengthType(signal.value)"
                size="small"
              >
                {{ getSignalStrengthLabel(signal.value) }}
              </el-tag>
            </div>
            <div class="signal-value">
              <span class="value">{{ signal.value.toFixed(2) }}</span>
              <el-icon
                :color="getSignalDirectionColor(signal.value)"
                class="direction-icon"
              >
                <component :is="getSignalDirectionIcon(signal.value)" />
              </el-icon>
            </div>
            <el-progress
              :percentage="Math.min(Math.abs(signal.value) * 33.33, 100)"
              :color="getSignalColor(signal.value)"
              :show-text="false"
            />
          </el-card>
        </el-col>
      </el-row>
    </div>

    <!-- 市场背景信号 -->
    <div class="market-signals">
      <h4>市场背景信号</h4>
      <el-row :gutter="16">
        <el-col
          v-for="signal in marketSignals"
          :key="signal.name"
          :span="6"
        >
          <el-card
            class="signal-card"
            @mouseenter="handleSignalHover(signal.name, signal.value)"
          >
            <div class="signal-header">
              <span class="signal-name">{{ signal.name }}</span>
              <el-tag
                :type="getSignalStrengthType(signal.value)"
                size="small"
              >
                {{ getSignalStrengthLabel(signal.value) }}
              </el-tag>
            </div>
            <div class="signal-value">
              <span class="value">{{ signal.value.toFixed(2) }}</span>
              <el-icon
                :color="getSignalDirectionColor(signal.value)"
                class="direction-icon"
              >
                <component :is="getSignalDirectionIcon(signal.value)" />
              </el-icon>
            </div>
            <el-progress
              :percentage="Math.min(Math.abs(signal.value) * 33.33, 100)"
              :color="getSignalColor(signal.value)"
              :show-text="false"
            />
          </el-card>
        </el-col>
      </el-row>
    </div>

    <!-- 管理层可信度因子 -->
    <div class="management-factors">
      <h4>管理层可信度因子</h4>
      <el-row :gutter="16">
        <el-col
          v-for="factor in managementFactors"
          :key="factor.name"
          :span="6"
        >
          <el-card class="factor-card">
            <div class="factor-header">
              <span class="factor-name">{{ factor.name }}</span>
            </div>
            <div class="factor-value">
              <el-progress
                :percentage="factor.value * 100"
                :color="getFactorColor(factor.value)"
                :show-text="false"
              />
              <span class="value-text">{{ (factor.value * 100).toFixed(1) }}%</span>
            </div>
          </el-card>
        </el-col>
      </el-row>
    </div>

    <!-- 技术分析信号 -->
    <div class="technical-signals">
      <h4>技术分析信号</h4>
      <el-row :gutter="16">
        <el-col
          v-for="signal in technicalSignals"
          :key="signal.name"
          :span="6"
        >
          <el-card
            class="signal-card"
            @mouseenter="handleSignalHover(signal.name, signal.value)"
          >
            <div class="signal-header">
              <span class="signal-name">{{ signal.name }}</span>
            </div>
            <div class="signal-value">
              <span class="value">{{ signal.value.toFixed(2) }}</span>
            </div>
            <el-progress
              :percentage="Math.min(Math.abs(signal.value) * 10, 100)"
              :color="getTechnicalSignalColor(signal.name, signal.value)"
              :show-text="false"
            />
          </el-card>
        </el-col>
      </el-row>
    </div>

    <!-- 雷达图 -->
    <div
      v-if="latestSignal"
      class="radar-chart"
    >
      <h4>多维度信号雷达图</h4>
      <el-card>
        <div class="chart-container">
          <v-chart
            :option="radarChartOption"
            style="height: 400px;"
          />
        </div>
      </el-card>
    </div>

    <!-- 空状态 -->
    <el-empty
      v-if="!loading && data.length === 0"
      description="暂无量化信号数据"
    />

    <!-- 加载状态 -->
    <div
      v-if="loading"
      class="loading"
    >
      <el-skeleton
        :rows="4"
        animated
      />
    </div>

    <!-- 错误状态 -->
    <el-alert
      v-if="error"
      type="error"
      :title="error"
      show-icon
      closable
      @close="handleErrorClose"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { use } from 'echarts/core';
import { CanvasRenderer } from 'echarts/renderers';
import { RadarChart } from 'echarts/charts';
import {
  TitleComponent,
  TooltipComponent,
  LegendComponent,
  GridComponent
} from 'echarts/components';
import VChart from 'vue-echarts';
import { TrendCharts, TrendCharts as TrendDown } from '@element-plus/icons-vue';
import type { QuantSignalDashboardProps, QuantSignalsData } from '@/types/arbitration';

// 注册 ECharts 组件
use([
  CanvasRenderer,
  RadarChart,
  TitleComponent,
  TooltipComponent,
  LegendComponent,
  GridComponent
]);

// ==================== Props ====================
const props = withDefaults(defineProps<QuantSignalDashboardProps>(), {
  loading: false,
  error: null,
  onSignalHover: () => {},
  onSignalClick: () => {}
});

// ==================== 计算属性 ====================
const latestSignal = computed(() => {
  return props.data.length > 0 ? props.data[0] : null;
});

const individualSignals = computed(() => {
  if (!latestSignal.value) return [];

  return [
    { name: '收益率Z分数', value: latestSignal.value.returnZScore },
    { name: '成交量Z分数', value: latestSignal.value.volumeZScore },
    { name: '动量Z分数', value: latestSignal.value.momentumZScore },
    { name: '波动率Z分数', value: latestSignal.value.volatilityZScore }
  ];
});

const marketSignals = computed(() => {
  if (!latestSignal.value) return [];

  return [
    { name: '宏观风险Z分数', value: latestSignal.value.macroRiskZScore },
    { name: '市场风格Z分数', value: latestSignal.value.marketStyleZScore },
    { name: '行业轮动Z分数', value: latestSignal.value.industryRotationZScore },
    { name: '概念热度Z分数', value: latestSignal.value.conceptZScore }
  ];
});

const managementFactors = computed(() => {
  if (!latestSignal.value) return [];

  return [
    { name: 'MD&A履行率', value: latestSignal.value.mdaFulfillmentRate },
    { name: '管理层可信度', value: latestSignal.value.managementCredibilityScore },
    { name: '披露质量', value: latestSignal.value.disclosureQualityScore },
    { name: '财务透明度', value: latestSignal.value.financialTransparencyScore }
  ];
});

const technicalSignals = computed(() => {
  if (!latestSignal.value) return [];

  return [
    { name: 'RSI', value: latestSignal.value.rsi },
    { name: 'MACD信号', value: latestSignal.value.macdSignal },
    { name: '布林带位置', value: latestSignal.value.bollingerPosition },
    { name: '均线信号', value: latestSignal.value.maSignal }
  ];
});

const radarChartOption = computed(() => {
  if (!latestSignal.value) return {};

  const data = [
    {
      value: [
        Math.abs(latestSignal.value.returnZScore),
        Math.abs(latestSignal.value.volumeZScore),
        Math.abs(latestSignal.value.momentumZScore),
        Math.abs(latestSignal.value.volatilityZScore),
        Math.abs(latestSignal.value.macroRiskZScore),
        Math.abs(latestSignal.value.marketStyleZScore)
      ],
      name: '当前信号'
    }
  ];

  return {
    title: {
      text: '多维度信号强度',
      left: 'center'
    },
    tooltip: {},
    legend: {
      data: ['当前信号'],
      bottom: 0
    },
    radar: {
      indicator: [
        { name: '收益率', max: 3 },
        { name: '成交量', max: 3 },
        { name: '动量', max: 3 },
        { name: '波动率', max: 3 },
        { name: '宏观风险', max: 3 },
        { name: '市场风格', max: 3 }
      ]
    },
    series: [
      {
        name: '信号强度',
        type: 'radar',
        data: data
      }
    ]
  };
});

// ==================== 方法 ====================
const handleSignalHover = (signal: string, value: number) => {
  props.onSignalHover?.(signal, value);
};

const getSignalStatusType = (status: string) => {
  const types: Record<string, string> = {
    active: 'success',
    expired: 'warning',
    cancelled: 'danger',
    archived: 'info'
  };
  return types[status] || 'info';
};

const getSignalStatusLabel = (status: string) => {
  const labels: Record<string, string> = {
    active: '活跃',
    expired: '已过期',
    cancelled: '已取消',
    archived: '已归档'
  };
  return labels[status] || status;
};

const getSignalStrengthType = (value: number) => {
  const absValue = Math.abs(value);
  if (absValue >= 2) return 'danger';
  if (absValue >= 1.5) return 'warning';
  if (absValue >= 1) return 'success';
  return 'info';
};

const getSignalStrengthLabel = (value: number) => {
  const absValue = Math.abs(value);
  if (absValue >= 2) return '强';
  if (absValue >= 1.5) return '中';
  if (absValue >= 1) return '弱';
  return '中性';
};

const getSignalDirectionColor = (value: number) => {
  if (value > 0) return '#67c23a';
  if (value < 0) return '#f56c6c';
  return '#909399';
};

const getSignalDirectionIcon = (value: number) => {
  if (value > 0) return 'TrendCharts';
  if (value < 0) return 'TrendDown';
  return 'Minus';
};

const getSignalColor = (value: number) => {
  if (value > 0) return '#67c23a';
  if (value < 0) return '#f56c6c';
  return '#909399';
};

const getFactorColor = (value: number) => {
  if (value >= 0.8) return '#67c23a';
  if (value >= 0.6) return '#e6a23c';
  return '#f56c6c';
};

const getTechnicalSignalColor = (name: string, value: number) => {
  if (name === 'RSI') {
    if (value >= 70) return '#f56c6c';
    if (value <= 30) return '#67c23a';
    return '#e6a23c';
  }
  return getSignalColor(value);
};

const handleErrorClose = () => {
  // 错误处理逻辑
};
</script>

<style scoped>
.quant-signal-dashboard {
  height: 100%;
  overflow-y: auto;
}

.signal-overview {
  margin-bottom: 24px;
}

.overview-card .card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.overview-card .card-header h3 {
  margin: 0;
  color: #333;
}

.individual-signals,
.market-signals,
.management-factors,
.technical-signals {
  margin-bottom: 24px;
}

h4 {
  margin: 0 0 16px 0;
  color: #333;
  font-size: 16px;
  font-weight: 600;
}

.signal-card,
.factor-card {
  height: 120px;
  cursor: pointer;
  transition: all 0.3s ease;
}

.signal-card:hover,
.factor-card:hover {
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
}

.signal-header,
.factor-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 8px;
}

.signal-name,
.factor-name {
  font-size: 14px;
  font-weight: 500;
  color: #333;
}

.signal-value {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 8px;
}

.value {
  font-size: 20px;
  font-weight: 600;
  color: #333;
}

.direction-icon {
  font-size: 16px;
}

.factor-value {
  display: flex;
  align-items: center;
  gap: 8px;
}

.value-text {
  font-size: 12px;
  color: #666;
  min-width: 40px;
}

.radar-chart {
  margin-bottom: 24px;
}

.chart-container {
  background: #fff;
  border-radius: 6px;
  padding: 16px;
}

.loading {
  padding: 20px;
}

/* 滚动条样式 */
.quant-signal-dashboard::-webkit-scrollbar {
  width: 6px;
}

.quant-signal-dashboard::-webkit-scrollbar-track {
  background: #f1f1f1;
  border-radius: 3px;
}

.quant-signal-dashboard::-webkit-scrollbar-thumb {
  background: #c1c1c1;
  border-radius: 3px;
}

.quant-signal-dashboard::-webkit-scrollbar-thumb:hover {
  background: #a8a8a8;
}
</style>
